// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Connect(arg1) {
  return window['go']['main']['App']['Connect'](arg1);
}

export function Disconnect(arg1) {
  return window['go']['main']['App']['Disconnect'](arg1);
}

export function GetProfile() {
  return window['go']['main']['App']['GetProfile']();
}

export function GetSystemHealth() {
  return window['go']['main']['App']['GetSystemHealth']();
}

export function TerminateProcesses(arg1) {
  return window['go']['main']['App']['TerminateProcesses'](arg1);
}
