// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function Connect(arg1:models.ConnectPayload):Promise<models.ConnectResponse>;

export function Disconnect(arg1:string):Promise<models.ConnectResponse>;

export function GetProfile():Promise<models.ProfileResponse>;

export function GetSystemHealth():Promise<models.SystemHealthResponse>;

export function SaveProfile(arg1:models.Profile):Promise<void>;

export function TerminateProcesses(arg1:Array<string>):Promise<void>;
